### PR TITLE
Init functionality by adding a small CLI

### PR DESCRIPTION
**Pull request by 0xfourzerofour**
Simple code generation that allows you to enter the following command

```
cargo run --package cli -- --strategy-name {NAME}
```

this will generate a new base strategy to make it easier to develop faster.

the implementation could be a lot cleaner and I think this should be added into the base artemis command however I thought I would start a discussion on that within this thread because it may change a bit overtime. I am a big fan of how the forge library and cli is set up and we could migrate to something similar to allow for more cli additions

### CODE REVIEW

**Comment by 0xfourzerofour** [comment]
@FrankieIsLost @pistomat related to #13

**Comment by ethercocktail** [comment]
great PR, had an lil error so changed the command to `cargo run --package cli -- --strategy-name {NAME}` to make it work ;)

**Comment by 0xfourzerofour** [comment]
> great PR, had an lil error so changed the command to `cargo run --package cli -- --strategy-name {NAME}` to make it work ;)

yeh sorry I forgot to add that part. Thank you!

**Comment by pistomat** [comment]
Nice! Works great 🚀🚀

**Review by FrankieIsLost — APPROVED** [review]

**Pull request merged**
